import { useState } from "react";
import "../public/css/App.css"

function App() {
    const [students, setAllstudents] = useState([
        {
            rollno: 7165,
            firstname: "shruti",
            lastname: "kathiriya",
            age: 20,
            phone: "3452677382",
            address: "Surat",
            class: "12th",
            division: "A",
            schoolname: "kaushal vidhyabhavan",
            medium:"Gujarati",
            schoolCode:"sv002",
        },{
    "rollno": 7100,
    "firstname": "Riya",
    "lastname": "Kathiriya",
    "age": 19,
    "class": "11th",
    "division": "B",
    "schoolname": "Global Academy",
    "address": "Bhavnagar",
    "phone": "9643876473",
    "schoolCode": "SCH100",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7101,
    "firstname": "Neha",
    "lastname": "Trivedi",
    "age": 20,
    "class": "11th",
    "division": "A",
    "schoolname": "Bright School",
    "address": "Rajkot",
    "phone": "7969354239",
    "schoolCode": "SCH101",
    "principalName": "Mrs. Rekha Shah",
    "medium": "English"
  },
  {
    "rollno": 7102,
    "firstname": "Pooja",
    "lastname": "Bhatt",
    "age": 17,
    "class": "11th",
    "division": "D",
    "schoolname": "Modern School",
    "address": "Gandhinagar",
    "phone": "8728741239",
    "schoolCode": "SCH102",
    "principalName": "Mrs. Rekha Shah",
    "medium": "English"
  },
  {
    "rollno": 7103,
    "firstname": "Mihir",
    "lastname": "Trivedi",
    "age": 20,
    "class": "12th",
    "division": "B",
    "schoolname": "Swaminarayan School",
    "address": "Bhavnagar",
    "phone": "9136100247",
    "schoolCode": "SCH103",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Gujarati"
  },
  {
    "rollno": 7104,
    "firstname": "Neha",
    "lastname": "Patel",
    "age": 20,
    "class": "11th",
    "division": "C",
    "schoolname": "Swaminarayan School",
    "address": "Vadodara",
    "phone": "7301034304",
    "schoolCode": "SCH104",
    "principalName": "Mr. Harsh Desai",
    "medium": "Gujarati"
  },
  {
    "rollno": 7105,
    "firstname": "Neha",
    "lastname": "Kathiriya",
    "age": 18,
    "class": "11th",
    "division": "C",
    "schoolname": "Global Academy",
    "address": "Surat",
    "phone": "7002904576",
    "schoolCode": "SCH105",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Hindi"
  },
  {
    "rollno": 7106,
    "firstname": "Aarav",
    "lastname": "Shah",
    "age": 18,
    "class": "12th",
    "division": "C",
    "schoolname": "Modern School",
    "address": "Gandhinagar",
    "phone": "9374150738",
    "schoolCode": "SCH106",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7107,
    "firstname": "Ravi",
    "lastname": "Rathod",
    "age": 18,
    "class": "12th",
    "division": "B",
    "schoolname": "Bright School",
    "address": "Ahmedabad",
    "phone": "7921949271",
    "schoolCode": "SCH107",
    "principalName": "Mr. Ramesh Patel",
    "medium": "English"
  },
  {
    "rollno": 7108,
    "firstname": "Komal",
    "lastname": "Joshi",
    "age": 19,
    "class": "12th",
    "division": "B",
    "schoolname": "Global Academy",
    "address": "Vapi",
    "phone": "7506796612",
    "schoolCode": "SCH108",
    "principalName": "Mr. Ramesh Patel",
    "medium": "English"
  },
  {
    "rollno": 7109,
    "firstname": "Aarav",
    "lastname": "Patel",
    "age": 18,
    "class": "12th",
    "division": "B",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Navsari",
    "phone": "7467687440",
    "schoolCode": "SCH109",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7110,
    "firstname": "Ravi",
    "lastname": "Shah",
    "age": 18,
    "class": "11th",
    "division": "B",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Rajkot",
    "phone": "8653276226",
    "schoolCode": "SCH110",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7111,
    "firstname": "Pooja",
    "lastname": "Patel",
    "age": 20,
    "class": "11th",
    "division": "B",
    "schoolname": "Modern School",
    "address": "Bhavnagar",
    "phone": "8497636253",
    "schoolCode": "SCH111",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Gujarati"
  },
  {
    "rollno": 7112,
    "firstname": "Ravi",
    "lastname": "Chauhan",
    "age": 20,
    "class": "11th",
    "division": "A",
    "schoolname": "Global Academy",
    "address": "Gandhinagar",
    "phone": "9624428108",
    "schoolCode": "SCH112",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7113,
    "firstname": "Neha",
    "lastname": "Joshi",
    "age": 19,
    "class": "11th",
    "division": "D",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Bhavnagar",
    "phone": "8770913684",
    "schoolCode": "SCH113",
    "principalName": "Mr. Harsh Desai",
    "medium": "Hindi"
  },
  {
    "rollno": 7114,
    "firstname": "Pooja",
    "lastname": "Kathiriya",
    "age": 18,
    "class": "12th",
    "division": "A",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Bhavnagar",
    "phone": "7913655144",
    "schoolCode": "SCH114",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Hindi"
  },
  {
    "rollno": 7115,
    "firstname": "Ravi",
    "lastname": "Patel",
    "age": 20,
    "class": "12th",
    "division": "C",
    "schoolname": "Modern School",
    "address": "Surat",
    "phone": "9260311950",
    "schoolCode": "SCH115",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Hindi"
  },
  {
    "rollno": 7116,
    "firstname": "Riya",
    "lastname": "Joshi",
    "age": 19,
    "class": "12th",
    "division": "B",
    "schoolname": "Modern School",
    "address": "Anand",
    "phone": "9776661512",
    "schoolCode": "SCH116",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Hindi"
  },
  {
    "rollno": 7117,
    "firstname": "Riya",
    "lastname": "Kathiriya",
    "age": 17,
    "class": "11th",
    "division": "B",
    "schoolname": "Bright School",
    "address": "Anand",
    "phone": "9105120471",
    "schoolCode": "SCH117",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7118,
    "firstname": "Shruti",
    "lastname": "Trivedi",
    "age": 20,
    "class": "12th",
    "division": "C",
    "schoolname": "Modern School",
    "address": "Bhavnagar",
    "phone": "9632062696",
    "schoolCode": "SCH118",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Hindi"
  },
  {
    "rollno": 7119,
    "firstname": "Riya",
    "lastname": "Trivedi",
    "age": 18,
    "class": "12th",
    "division": "D",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Surat",
    "phone": "9174861289",
    "schoolCode": "SCH119",
    "principalName": "Mr. Harsh Desai",
    "medium": "Hindi"
  },
  {
    "rollno": 7120,
    "firstname": "Riya",
    "lastname": "Kathiriya",
    "age": 18,
    "class": "12th",
    "division": "D",
    "schoolname": "Global Academy",
    "address": "Gandhinagar",
    "phone": "8281974011",
    "schoolCode": "SCH120",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Hindi"
  },
  {
    "rollno": 7121,
    "firstname": "Shruti",
    "lastname": "Trivedi",
    "age": 20,
    "class": "11th",
    "division": "B",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Ahmedabad",
    "phone": "8346028646",
    "schoolCode": "SCH121",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7122,
    "firstname": "Riya",
    "lastname": "Rathod",
    "age": 18,
    "class": "11th",
    "division": "A",
    "schoolname": "Swaminarayan School",
    "address": "Bhavnagar",
    "phone": "9712509855",
    "schoolCode": "SCH122",
    "principalName": "Mr. Harsh Desai",
    "medium": "Gujarati"
  },
  {
    "rollno": 7123,
    "firstname": "Ravi",
    "lastname": "Chauhan",
    "age": 20,
    "class": "12th",
    "division": "C",
    "schoolname": "Swaminarayan School",
    "address": "Navsari",
    "phone": "9431503218",
    "schoolCode": "SCH123",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7124,
    "firstname": "Ravi",
    "lastname": "Shah",
    "age": 17,
    "class": "11th",
    "division": "A",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Navsari",
    "phone": "8668611575",
    "schoolCode": "SCH124",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7125,
    "firstname": "Karan",
    "lastname": "Joshi",
    "age": 17,
    "class": "12th",
    "division": "D",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Rajkot",
    "phone": "8001422655",
    "schoolCode": "SCH125",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7126,
    "firstname": "Karan",
    "lastname": "Rathod",
    "age": 20,
    "class": "12th",
    "division": "B",
    "schoolname": "Swaminarayan School",
    "address": "Bhavnagar",
    "phone": "7543596409",
    "schoolCode": "SCH126",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "English"
  },
  {
    "rollno": 7127,
    "firstname": "Riya",
    "lastname": "Mehta",
    "age": 17,
    "class": "11th",
    "division": "A",
    "schoolname": "Swaminarayan School",
    "address": "Bhavnagar",
    "phone": "7374748615",
    "schoolCode": "SCH127",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "English"
  },
  {
    "rollno": 7128,
    "firstname": "Shruti",
    "lastname": "Chauhan",
    "age": 19,
    "class": "12th",
    "division": "B",
    "schoolname": "Swaminarayan School",
    "address": "Vadodara",
    "phone": "8163722834",
    "schoolCode": "SCH128",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Hindi"
  },
  {
    "rollno": 7129,
    "firstname": "Komal",
    "lastname": "Shah",
    "age": 19,
    "class": "11th",
    "division": "A",
    "schoolname": "Bright School",
    "address": "Navsari",
    "phone": "7385759220",
    "schoolCode": "SCH129",
    "principalName": "Mrs. Meena Joshi",
    "medium": "English"
  },
  {
    "rollno": 7130,
    "firstname": "Riya",
    "lastname": "Joshi",
    "age": 19,
    "class": "11th",
    "division": "B",
    "schoolname": "Bright School",
    "address": "Bhavnagar",
    "phone": "8954059858",
    "schoolCode": "SCH130",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7131,
    "firstname": "Komal",
    "lastname": "Trivedi",
    "age": 17,
    "class": "11th",
    "division": "A",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Navsari",
    "phone": "8495560171",
    "schoolCode": "SCH131",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Hindi"
  },
  {
    "rollno": 7132,
    "firstname": "Mihir",
    "lastname": "Rathod",
    "age": 19,
    "class": "11th",
    "division": "C",
    "schoolname": "Swaminarayan School",
    "address": "Vapi",
    "phone": "7212232828",
    "schoolCode": "SCH132",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7133,
    "firstname": "Komal",
    "lastname": "Mehta",
    "age": 19,
    "class": "12th",
    "division": "D",
    "schoolname": "Bright School",
    "address": "Ahmedabad",
    "phone": "8431966242",
    "schoolCode": "SCH133",
    "principalName": "Mr. Ramesh Patel",
    "medium": "English"
  },
  {
    "rollno": 7134,
    "firstname": "Riya",
    "lastname": "Mehta",
    "age": 17,
    "class": "11th",
    "division": "C",
    "schoolname": "Swaminarayan School",
    "address": "Navsari",
    "phone": "9160103403",
    "schoolCode": "SCH134",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7135,
    "firstname": "Ravi",
    "lastname": "Bhatt",
    "age": 18,
    "class": "11th",
    "division": "B",
    "schoolname": "Modern School",
    "address": "Vapi",
    "phone": "8328172527",
    "schoolCode": "SCH135",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Hindi"
  },
  {
    "rollno": 7136,
    "firstname": "Pooja",
    "lastname": "Trivedi",
    "age": 20,
    "class": "12th",
    "division": "A",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Surat",
    "phone": "7144810190",
    "schoolCode": "SCH136",
    "principalName": "Mrs. Meena Joshi",
    "medium": "English"
  },
  {
    "rollno": 7137,
    "firstname": "Aarav",
    "lastname": "Bhatt",
    "age": 18,
    "class": "12th",
    "division": "B",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Bhavnagar",
    "phone": "9518197091",
    "schoolCode": "SCH137",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Hindi"
  },
  {
    "rollno": 7138,
    "firstname": "Neha",
    "lastname": "Kathiriya",
    "age": 20,
    "class": "11th",
    "division": "B",
    "schoolname": "Bright School",
    "address": "Vapi",
    "phone": "8521665643",
    "schoolCode": "SCH138",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7139,
    "firstname": "Pooja",
    "lastname": "Bhatt",
    "age": 17,
    "class": "11th",
    "division": "C",
    "schoolname": "Global Academy",
    "address": "Gandhinagar",
    "phone": "8205744566",
    "schoolCode": "SCH139",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7140,
    "firstname": "Mihir",
    "lastname": "Patel",
    "age": 19,
    "class": "11th",
    "division": "C",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Vapi",
    "phone": "7025823059",
    "schoolCode": "SCH140",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Hindi"
  },
  {
    "rollno": 7141,
    "firstname": "Pooja",
    "lastname": "Joshi",
    "age": 17,
    "class": "12th",
    "division": "A",
    "schoolname": "Bright School",
    "address": "Anand",
    "phone": "9971576174",
    "schoolCode": "SCH141",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7142,
    "firstname": "Karan",
    "lastname": "Joshi",
    "age": 17,
    "class": "12th",
    "division": "C",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Ahmedabad",
    "phone": "9274326156",
    "schoolCode": "SCH142",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "English"
  },
  {
    "rollno": 7143,
    "firstname": "Komal",
    "lastname": "Patel",
    "age": 18,
    "class": "11th",
    "division": "C",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Surat",
    "phone": "9841858464",
    "schoolCode": "SCH143",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7144,
    "firstname": "Pooja",
    "lastname": "Trivedi",
    "age": 19,
    "class": "12th",
    "division": "B",
    "schoolname": "Bright School",
    "address": "Vadodara",
    "phone": "8343751494",
    "schoolCode": "SCH144",
    "principalName": "Mr. Nirav Mehta",
    "medium": "English"
  },
  {
    "rollno": 7145,
    "firstname": "Aarav",
    "lastname": "Desai",
    "age": 20,
    "class": "12th",
    "division": "B",
    "schoolname": "Global Academy",
    "address": "Ahmedabad",
    "phone": "9359650893",
    "schoolCode": "SCH145",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Gujarati"
  },
  {
    "rollno": 7146,
    "firstname": "Ravi",
    "lastname": "Bhatt",
    "age": 18,
    "class": "11th",
    "division": "A",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Ahmedabad",
    "phone": "7362373878",
    "schoolCode": "SCH146",
    "principalName": "Mr. Ramesh Patel",
    "medium": "English"
  },
  {
    "rollno": 7147,
    "firstname": "Vivek",
    "lastname": "Chauhan",
    "age": 18,
    "class": "12th",
    "division": "A",
    "schoolname": "Modern School",
    "address": "Surat",
    "phone": "8801091407",
    "schoolCode": "SCH147",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7148,
    "firstname": "Ravi",
    "lastname": "Kathiriya",
    "age": 20,
    "class": "11th",
    "division": "C",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Navsari",
    "phone": "7206844416",
    "schoolCode": "SCH148",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7149,
    "firstname": "Komal",
    "lastname": "Mehta",
    "age": 20,
    "class": "12th",
    "division": "A",
    "schoolname": "Bright School",
    "address": "Anand",
    "phone": "8041802581",
    "schoolCode": "SCH149",
    "principalName": "Mr. Harsh Desai",
    "medium": "Gujarati"
  },
  {
    "rollno": 7150,
    "firstname": "Aarav",
    "lastname": "Shah",
    "age": 19,
    "class": "11th",
    "division": "C",
    "schoolname": "Modern School",
    "address": "Anand",
    "phone": "9267449112",
    "schoolCode": "SCH150",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Hindi"
  },
  {
    "rollno": 7151,
    "firstname": "Komal",
    "lastname": "Rathod",
    "age": 18,
    "class": "11th",
    "division": "B",
    "schoolname": "Swaminarayan School",
    "address": "Ahmedabad",
    "phone": "7741224804",
    "schoolCode": "SCH151",
    "principalName": "Mr. Harsh Desai",
    "medium": "Hindi"
  },
  {
    "rollno": 7152,
    "firstname": "Riya",
    "lastname": "Shah",
    "age": 20,
    "class": "12th",
    "division": "C",
    "schoolname": "Swaminarayan School",
    "address": "Vadodara",
    "phone": "9135338246",
    "schoolCode": "SCH152",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Gujarati"
  },
  {
    "rollno": 7153,
    "firstname": "Komal",
    "lastname": "Desai",
    "age": 18,
    "class": "11th",
    "division": "C",
    "schoolname": "Modern School",
    "address": "Vadodara",
    "phone": "9658569147",
    "schoolCode": "SCH153",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Hindi"
  },
  {
    "rollno": 7154,
    "firstname": "Ravi",
    "lastname": "Rathod",
    "age": 17,
    "class": "11th",
    "division": "A",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Bhavnagar",
    "phone": "8801950039",
    "schoolCode": "SCH154",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Hindi"
  },
  {
    "rollno": 7155,
    "firstname": "Komal",
    "lastname": "Joshi",
    "age": 19,
    "class": "12th",
    "division": "C",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Surat",
    "phone": "8141761672",
    "schoolCode": "SCH155",
    "principalName": "Mr. Harsh Desai",
    "medium": "English"
  },
  {
    "rollno": 7156,
    "firstname": "Aarav",
    "lastname": "Chauhan",
    "age": 20,
    "class": "12th",
    "division": "C",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Junagadh",
    "phone": "7349630528",
    "schoolCode": "SCH156",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7157,
    "firstname": "Karan",
    "lastname": "Trivedi",
    "age": 17,
    "class": "12th",
    "division": "A",
    "schoolname": "Modern School",
    "address": "Ahmedabad",
    "phone": "8018730075",
    "schoolCode": "SCH157",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7158,
    "firstname": "Aarav",
    "lastname": "Bhatt",
    "age": 18,
    "class": "11th",
    "division": "D",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Vadodara",
    "phone": "9810721255",
    "schoolCode": "SCH158",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7159,
    "firstname": "Riya",
    "lastname": "Trivedi",
    "age": 20,
    "class": "12th",
    "division": "A",
    "schoolname": "Global Academy",
    "address": "Anand",
    "phone": "9241507332",
    "schoolCode": "SCH159",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Hindi"
  },
  {
    "rollno": 7160,
    "firstname": "Mihir",
    "lastname": "Trivedi",
    "age": 17,
    "class": "11th",
    "division": "A",
    "schoolname": "Global Academy",
    "address": "Surat",
    "phone": "9640017150",
    "schoolCode": "SCH160",
    "principalName": "Mr. Nirav Mehta",
    "medium": "English"
  },
  {
    "rollno": 7161,
    "firstname": "Mihir",
    "lastname": "Mehta",
    "age": 19,
    "class": "12th",
    "division": "A",
    "schoolname": "Swaminarayan School",
    "address": "Bhavnagar",
    "phone": "8674396500",
    "schoolCode": "SCH161",
    "principalName": "Mrs. Rekha Shah",
    "medium": "English"
  },
  {
    "rollno": 7162,
    "firstname": "Riya",
    "lastname": "Trivedi",
    "age": 20,
    "class": "11th",
    "division": "A",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Gandhinagar",
    "phone": "7240800909",
    "schoolCode": "SCH162",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7163,
    "firstname": "Neha",
    "lastname": "Bhatt",
    "age": 20,
    "class": "11th",
    "division": "B",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Navsari",
    "phone": "8247706988",
    "schoolCode": "SCH163",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Hindi"
  },
  {
    "rollno": 7164,
    "firstname": "Ravi",
    "lastname": "Trivedi",
    "age": 20,
    "class": "11th",
    "division": "A",
    "schoolname": "Modern School",
    "address": "Rajkot",
    "phone": "8070562438",
    "schoolCode": "SCH164",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7165,
    "firstname": "Ravi",
    "lastname": "Joshi",
    "age": 18,
    "class": "11th",
    "division": "B",
    "schoolname": "Modern School",
    "address": "Rajkot",
    "phone": "8895754122",
    "schoolCode": "SCH165",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7166,
    "firstname": "Shruti",
    "lastname": "Joshi",
    "age": 19,
    "class": "11th",
    "division": "D",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Anand",
    "phone": "9359428133",
    "schoolCode": "SCH166",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7167,
    "firstname": "Neha",
    "lastname": "Trivedi",
    "age": 18,
    "class": "11th",
    "division": "A",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Surat",
    "phone": "9423300912",
    "schoolCode": "SCH167",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "English"
  },
  {
    "rollno": 7168,
    "firstname": "Shruti",
    "lastname": "Mehta",
    "age": 18,
    "class": "11th",
    "division": "D",
    "schoolname": "Bright School",
    "address": "Gandhinagar",
    "phone": "7299451564",
    "schoolCode": "SCH168",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7169,
    "firstname": "Riya",
    "lastname": "Mehta",
    "age": 18,
    "class": "11th",
    "division": "B",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Junagadh",
    "phone": "9890723699",
    "schoolCode": "SCH169",
    "principalName": "Mr. Harsh Desai",
    "medium": "English"
  },
  {
    "rollno": 7170,
    "firstname": "Riya",
    "lastname": "Patel",
    "age": 20,
    "class": "11th",
    "division": "C",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Bhavnagar",
    "phone": "9275985523",
    "schoolCode": "SCH170",
    "principalName": "Mr. Nirav Mehta",
    "medium": "English"
  },
  {
    "rollno": 7171,
    "firstname": "Mihir",
    "lastname": "Desai",
    "age": 17,
    "class": "12th",
    "division": "A",
    "schoolname": "Bright School",
    "address": "Ahmedabad",
    "phone": "9547323423",
    "schoolCode": "SCH171",
    "principalName": "Mr. Harsh Desai",
    "medium": "English"
  },
  {
    "rollno": 7172,
    "firstname": "Aarav",
    "lastname": "Joshi",
    "age": 20,
    "class": "12th",
    "division": "D",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Junagadh",
    "phone": "9758586227",
    "schoolCode": "SCH172",
    "principalName": "Mrs. Rekha Shah",
    "medium": "English"
  },
  {
    "rollno": 7173,
    "firstname": "Shruti",
    "lastname": "Mehta",
    "age": 20,
    "class": "11th",
    "division": "D",
    "schoolname": "Modern School",
    "address": "Gandhinagar",
    "phone": "7539744048",
    "schoolCode": "SCH173",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7174,
    "firstname": "Ravi",
    "lastname": "Bhatt",
    "age": 18,
    "class": "11th",
    "division": "C",
    "schoolname": "Bright School",
    "address": "Anand",
    "phone": "9241570746",
    "schoolCode": "SCH174",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7175,
    "firstname": "Mihir",
    "lastname": "Chauhan",
    "age": 18,
    "class": "12th",
    "division": "A",
    "schoolname": "Swaminarayan School",
    "address": "Anand",
    "phone": "9300089164",
    "schoolCode": "SCH175",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Hindi"
  },
  {
    "rollno": 7176,
    "firstname": "Ravi",
    "lastname": "Patel",
    "age": 19,
    "class": "12th",
    "division": "D",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Vapi",
    "phone": "9869915502",
    "schoolCode": "SCH176",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7177,
    "firstname": "Ravi",
    "lastname": "Bhatt",
    "age": 17,
    "class": "12th",
    "division": "D",
    "schoolname": "Global Academy",
    "address": "Bhavnagar",
    "phone": "9220006670",
    "schoolCode": "SCH177",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7178,
    "firstname": "Pooja",
    "lastname": "Shah",
    "age": 17,
    "class": "12th",
    "division": "B",
    "schoolname": "Global Academy",
    "address": "Bhavnagar",
    "phone": "7023210243",
    "schoolCode": "SCH178",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7179,
    "firstname": "Komal",
    "lastname": "Patel",
    "age": 20,
    "class": "11th",
    "division": "B",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Gandhinagar",
    "phone": "7100001834",
    "schoolCode": "SCH179",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Hindi"
  },
  {
    "rollno": 7180,
    "firstname": "Pooja",
    "lastname": "Joshi",
    "age": 19,
    "class": "12th",
    "division": "D",
    "schoolname": "Bright School",
    "address": "Anand",
    "phone": "9813664905",
    "schoolCode": "SCH180",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Gujarati"
  },
  {
    "rollno": 7181,
    "firstname": "Pooja",
    "lastname": "Rathod",
    "age": 19,
    "class": "11th",
    "division": "D",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Bhavnagar",
    "phone": "8745260051",
    "schoolCode": "SCH181",
    "principalName": "Mrs. Rekha Shah",
    "medium": "Hindi"
  },
  {
    "rollno": 7182,
    "firstname": "Ravi",
    "lastname": "Patel",
    "age": 18,
    "class": "11th",
    "division": "A",
    "schoolname": "Modern School",
    "address": "Junagadh",
    "phone": "7008923432",
    "schoolCode": "SCH182",
    "principalName": "Mrs. Meena Joshi",
    "medium": "Hindi"
  },
  {
    "rollno": 7183,
    "firstname": "Pooja",
    "lastname": "Patel",
    "age": 20,
    "class": "12th",
    "division": "D",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Anand",
    "phone": "7934208742",
    "schoolCode": "SCH183",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7184,
    "firstname": "Vivek",
    "lastname": "Joshi",
    "age": 19,
    "class": "12th",
    "division": "B",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Ahmedabad",
    "phone": "9439287255",
    "schoolCode": "SCH184",
    "principalName": "Mrs. Meena Joshi",
    "medium": "English"
  },
  {
    "rollno": 7185,
    "firstname": "Ravi",
    "lastname": "Patel",
    "age": 19,
    "class": "12th",
    "division": "B",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Vadodara",
    "phone": "8734689701",
    "schoolCode": "SCH185",
    "principalName": "Mr. Harsh Desai",
    "medium": "Hindi"
  },
  {
    "rollno": 7186,
    "firstname": "Karan",
    "lastname": "Mehta",
    "age": 17,
    "class": "12th",
    "division": "C",
    "schoolname": "Bright School",
    "address": "Gandhinagar",
    "phone": "9171651381",
    "schoolCode": "SCH186",
    "principalName": "Mr. Harsh Desai",
    "medium": "English"
  },
  {
    "rollno": 7187,
    "firstname": "Shruti",
    "lastname": "Mehta",
    "age": 19,
    "class": "12th",
    "division": "B",
    "schoolname": "Sardar Vidhyalaya",
    "address": "Surat",
    "phone": "9494242044",
    "schoolCode": "SCH187",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7188,
    "firstname": "Shruti",
    "lastname": "Bhatt",
    "age": 18,
    "class": "11th",
    "division": "C",
    "schoolname": "Modern School",
    "address": "Ahmedabad",
    "phone": "8937158231",
    "schoolCode": "SCH188",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Hindi"
  },
  {
    "rollno": 7189,
    "firstname": "Pooja",
    "lastname": "Rathod",
    "age": 18,
    "class": "12th",
    "division": "A",
    "schoolname": "Modern School",
    "address": "Anand",
    "phone": "9041926441",
    "schoolCode": "SCH189",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Hindi"
  },
  {
    "rollno": 7190,
    "firstname": "Ravi",
    "lastname": "Patel",
    "age": 18,
    "class": "12th",
    "division": "D",
    "schoolname": "Bright School",
    "address": "Vadodara",
    "phone": "9476095545",
    "schoolCode": "SCH190",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Hindi"
  },
  {
    "rollno": 7191,
    "firstname": "Pooja",
    "lastname": "Desai",
    "age": 20,
    "class": "11th",
    "division": "C",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Rajkot",
    "phone": "9336796894",
    "schoolCode": "SCH191",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Hindi"
  },
  {
    "rollno": 7192,
    "firstname": "Neha",
    "lastname": "Chauhan",
    "age": 19,
    "class": "12th",
    "division": "D",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Navsari",
    "phone": "9881669524",
    "schoolCode": "SCH192",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Gujarati"
  },
  {
    "rollno": 7193,
    "firstname": "Shruti",
    "lastname": "Kathiriya",
    "age": 20,
    "class": "11th",
    "division": "D",
    "schoolname": "Modern School",
    "address": "Junagadh",
    "phone": "7990916254",
    "schoolCode": "SCH193",
    "principalName": "Mrs. Meena Joshi",
    "medium": "English"
  },
  {
    "rollno": 7194,
    "firstname": "Komal",
    "lastname": "Trivedi",
    "age": 18,
    "class": "12th",
    "division": "D",
    "schoolname": "Kaushal Vidhyabhavan",
    "address": "Vadodara",
    "phone": "9959088783",
    "schoolCode": "SCH194",
    "principalName": "Mr. Ramesh Patel",
    "medium": "Hindi"
  },
  {
    "rollno": 7195,
    "firstname": "Vivek",
    "lastname": "Kathiriya",
    "age": 20,
    "class": "12th",
    "division": "D",
    "schoolname": "Global Academy",
    "address": "Vadodara",
    "phone": "9362141596",
    "schoolCode": "SCH195",
    "principalName": "Mr. Nirav Mehta",
    "medium": "Hindi"
  },
  {
    "rollno": 7196,
    "firstname": "Shruti",
    "lastname": "Mehta",
    "age": 20,
    "class": "11th",
    "division": "A",
    "schoolname": "Bright School",
    "address": "Anand",
    "phone": "9398977856",
    "schoolCode": "SCH196",
    "principalName": "Mrs. Kiran Trivedi",
    "medium": "Gujarati"
  },
  {
    "rollno": 7197,
    "firstname": "Shruti",
    "lastname": "Kathiriya",
    "age": 20,
    "class": "11th",
    "division": "C",
    "schoolname": "Global Academy",
    "address": "Navsari",
    "phone": "7771242071",
    "schoolCode": "SCH197",
    "principalName": "Mr. Ramesh Patel",
    "medium": "English"
  },
  {
    "rollno": 7198,
    "firstname": "Pooja",
    "lastname": "Shah",
    "age": 20,
    "class": "11th",
    "division": "C",
    "schoolname": "Global Academy",
    "address": "Ahmedabad",
    "phone": "9602006834",
    "schoolCode": "SCH198",
    "principalName": "Mr. Ramesh Patel",
    "medium": "English"
  },
    ]);
    return (
        <>
            <h1>Student Table</h1>
            <table border="1" cellPadding="1" cellSpacing="0">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Roll No</th>
                        <th>First Name</th>
                        <th>Last Name</th>
                        <th>Age</th>
                        <th>phone</th>
                        <th>Adress</th>
                        <th>Class</th>
                        <th>Division</th>
                        <th>School Name</th>
                        <th>Medium</th>
                        <th>School code</th>
                    </tr>
                </thead>

                <tbody>
                    {students.map((stud, index) => (
                        <tr key={index}>
                            <td>{index + 1}</td>
                            <td>{stud.rollno}</td>
                            <td>{stud.firstname}</td>
                            <td>{stud.lastname}</td>
                            <td>{stud.age}</td>
                            <td>{stud.phone}</td>
                            <td>{stud.address}</td>
                            <td>{stud.class}</td>
                            <td>{stud.division}</td>
                            <td>{stud.schoolname}</td>
                            <td>{stud.medium}</td>
                            <td>{stud.schoolCode}</td>

                        </tr>
                    ))}
                </tbody>
            </table>
        </>
    );
}
export default App;